version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cineHidalgo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    driver: local
